/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game2;

import java.awt.Color;
import java.util.Random;
import javax.swing.*;
/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {
    int sign = 1;
    /**
     * Creates new form MainFrame
     */
    JButton jb[][] = new JButton[6][7];
    public MainFrame() {
        initComponents();
        jPanel1.setLayout(new java.awt.GridLayout(6, 7,4,4));
        for (int i = 0; i < jb.length; i++) {
            for (int j = 0; j < jb[0].length; j++) {
                jb[i][j] = new JButton();
                jb[i][j].setText("");
                jb[i][j].setSize(10,10);
                jPanel1.add(jb[i][j]);
                final int colIndex = j;  
                jb[i][j].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        colourSetter(colIndex);
                    }
                });
            }
        }
        Random ran = new Random();
        char randomChar = (char)('a' + ran.nextInt(26));

        if (randomChar > 'm') {
            sign = 1;  
            jLabel1.setText(NameSetter.player1 + "'s Turn");
            jButton1.setBackground(Color.BLUE);
        }
        else 
        {
            sign = -1;
            jLabel1.setText(NameSetter.player2 + "'s Turn");
            jButton1.setBackground(Color.RED);
        }
    }

public boolean checkDraw() 
{
    for (int i = 0; i < jb.length; i++) 
    {
        
        for (int j = 0; j < jb[0].length; j++) 
        {    
            Color bg = jb[i][j].getBackground();
            if (bg != Color.RED && bg != Color.BLUE) {
                return false;  
            }
        }
    }
    return true;  
}
public void disableButtons() 
{
    for (int i = 0; i < jb.length; i++) 
    {
        for (int j = 0; j < jb[0].length; j++) 
        {
            jb[i][j].setEnabled(false);
            jb[i][j].setBackground(Color.WHITE);
        }
    }
    jLabel1.setText("");
    jButton1.setVisible(false);
}
public void colourSetter(int col) 
{
    for (int row = jb.length - 1; row >= 0; row--) 
    {
        if (jb[row][col].getBackground() != Color.RED && jb[row][col].getBackground() != Color.BLUE) 
        {
            if (sign == 1) {
                jb[row][col].setBackground(Color.BLUE);
                jLabel1.setText(NameSetter.player2 + "'s Turn");
                jButton1.setBackground(Color.RED);
                sign = -1;
            }
            else 
            {
                jb[row][col].setBackground(Color.RED);
                jLabel1.setText(NameSetter.player1 + "'s Turn");
                jButton1.setBackground(Color.BLUE);
                sign = 1;
            }
            Color color = new Checker().checkWinner(jb);
            if (color != null) 
            {
                if (color.equals(Color.BLUE)) 
                {
                    JOptionPane.showMessageDialog(null, NameSetter.player1 + " is a winner!");
                    disableButtons();
                    jButton2.setEnabled(true);
                }
                else if (color.equals(Color.RED)) 
                {
                    JOptionPane.showMessageDialog(null, NameSetter.player2 + " is a winner!");
                    disableButtons();
                    jButton2.setEnabled(true);
                }
            }
            else if (checkDraw()) 
            {  
                JOptionPane.showMessageDialog(null, "It's a Draw!");
                disableButtons();
                jButton2.setEnabled(true);
            }
            break;  
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Turn");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 140, 350, 28);

        jPanel1.setBackground(new java.awt.Color(168, 226, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 190, 660, 340);

        jButton1.setEnabled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 130, 70, 40);

        jButton2.setBackground(new java.awt.Color(67, 198, 172));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PLAY AGAIN");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 130, 150, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/settings (1).png"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 120, 70, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Design (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 740, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        NameSetter mf = new NameSetter();
        mf.setVisible(true);
        mf.setSize(700,580);
        mf.setLocationRelativeTo(null);
        mf.setResizable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        mf.setSize(700,580);
        mf.setLocationRelativeTo(null);
        mf.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
